---
# Un playbook commence généralement par '---', ce qui indique le début d'un document YAML.
# Nom du playbook : Une description courte et significative de ce que fait le playbook.
- name: Playbook AterlierAnsible
  # Les hôtes sur lesquels le playbook sera exécuté. 
  hosts: target_ec2
  # Utiliser les privilèges d'administrateur pour exécuter les tâches. 
  # Si 'true', Ansible utilisera sudo (ou un mécanisme similaire) pour exécuter les commandes.
  become: true
  # Liste des tâches à exécuter. Chaque tâche est une action que Ansible effectuera sur les hôtes cibles.
  tasks:
    # PING sur tous les hôtes du fichier hosts.ini
    - name: Example from an Ansible Playbook
      ansible.builtin.ping:

    # PING sur tous les hôtes du fichier hosts.ini avec erreur induite
    - name: Induce an exception to see what happens
      ansible.builtin.ping:
        data: crash