---
# M2i - Olivier TENGHERIAN
#
# Un playbook commence généralement par '---', ce qui indique le début d'un document YAML.
# Nom du playbook : Une description courte et significative de ce que fait le playbook.
- name: Playbook AtelierAnsible
  # Les hôtes sur lesquels le playbook sera exécuté. 
  hosts: ec2
  become: true
  # Liste des tâches à exécuter
  tasks:
    # INSTALLER gcc-c++ ET make VIA yum
    - name: GCC | Install C++
      ansible.builtin.yum:
        name:
          - gcc-c++
          - make
        state: present
    # INSTALLER nodejs VIA yum
    # spécification de " enablerepo: epel " pour utiliser le dépôt EPEL souvent utilisé pour obtenir Node.js sur les systèmes basés sur YUM
    - name: NODE.js | Install
      ansible.builtin.yum:
        name: nodejs
        state: present
        enablerepo: epel  # Utiliser le dépôt EPEL pour Node.js
    # INSTALLER gatsby-cli VIA npm
    - name: gatsby-cli | Install
      ansible.builtin.npm:
        name: gatsby-cli
        state: present