---
# Un playbook commence généralement par '---', ce qui indique le début d'un document YAML.
# Nom du playbook : Une description courte et significative de ce que fait le playbook.
- name: Playbook AterlierAnsible
  # Les hôtes sur lesquels le playbook sera exécuté. 
  hosts: all
  # Utiliser les privilèges d'administrateur pour exécuter les tâches. 
  # Si 'true', Ansible utilisera sudo (ou un mécanisme similaire) pour exécuter les commandes.
  become: false
  # Liste des tâches à exécuter. Chaque tâche est une action que Ansible effectuera sur les hôtes cibles.
  tasks:
    # INSTALLER gcc-c++ ET make VIA yum
    - name: ping
        crash: data++++